name = "rplay"
main = "src/index.js"
compatibility_date = "2026-05-12"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

# =====================
# KV 新增绑定
# =====================
kv_namespaces = [
  { binding = "RP_KV", id = "RP" }
]

# =====================
# D1 新增绑定
# =====================
[[d1_databases]]
binding = "RP_DB"
database_name = "rplayD1"
database_id = "07dac755-52b2-4b0b-a149-88c335f963c1"
[[r2_buckets]]
binding = "RP_R2"
bucket_name = "rp-images"
